// Generated by FIR Compiler
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
// ************************************************************
// Copyright (C) 1991-2005 Altera Corporation
// Any megafunction design, and related net list (encrypted or decrypted),
// support information, device programming or simulation file, and any other
// associated documentation or information provided by Altera or a partner
// under Altera's Megafunction Partnership Program may be used only to
// program PLD devices (but not masked PLD devices) from Altera.  Any other
// use of such megafunction design, net list, support information, device
// programming or simulation file, or any other related documentation or
// information is prohibited for any other purpose, including, but not
// limited to modification, reverse engineering, de-compiling, or use with
// any other silicon devices, unless such use is explicitly licensed under
// a separate agreement with Altera or a megafunction partner.  Title to
// the intellectual property, including patents, copyrights, trademarks,
// trade secrets, or maskworks, embodied in any such megafunction design,
// net list, support information, device programming or simulation file, or
// any other related documentation or information provided by Altera or a
// megafunction partner, remains with Altera, the megafunction partner, or
// their respective licensors.  No other licenses, including any licenses
// needed under any third party's intellectual property, are provided herein.
// 00
// altera message_off 10036
(* altera_attribute = "-name MESSAGE_DISABLE 15400; -name MESSAGE_DISABLE 14130; -name MESSAGE_DISABLE 10036; -name MESSAGE_DISABLE 12020; -name MESSAGE_DISABLE 12030; -name MESSAGE_DISABLE 12010; -name MESSAGE_DISABLE 12110; -name MESSAGE_DISABLE 14320; -name MESSAGE_DISABLE 13410" *)
module demod_fir_st (clk, 
              rst, 
              data_in, 
              clk_en, 
              rdy_to_ld, 
              done, 
              fir_result); 
parameter DATA_WIDTH  = 8;
parameter COEF_WIDTH  = 9;
parameter ACCUM_WIDTH = 20;

input clk, rst;
input [DATA_WIDTH-1:0] data_in;
input clk_en;
output rdy_to_ld;
wire rdy_to_ld;
wire rdy_int;
wire data_ld;
output done;
wire done;
wire done_int;
output [ACCUM_WIDTH-1:0] fir_result;
wire addr_low;
assign addr_low = 1'b0;


//--- Parallel TDL Storage ---
wire inv_rst;
assign inv_rst = ~rst;
assign data_ld = rdy_int;
wire [7:0] tdl_0_n;
wire [7:0] tdl_1_n;
wire [7:0] tdl_2_n;
wire [7:0] tdl_3_n;
wire [7:0] tdl_4_n;
wire [7:0] tdl_5_n;
wire [7:0] tdl_6_n;
wire [7:0] tdl_7_n;
wire [7:0] tdl_8_n;
wire [7:0] tdl_9_n;
wire [7:0] tdl_10_n;
wire [7:0] tdl_11_n;
wire [7:0] tdl_12_n;
wire [7:0] tdl_13_n;
wire [7:0] tdl_14_n;
wire [7:0] tdl_15_n;


//--- TDL  ---
tdl_da_lc Utdldalc0n (.clk(clk), .clk_en(rdy_int & clk_en),.rst(rst),.data_in(data_in), .data_out(tdl_0_n) );
defparam Utdldalc0n.WIDTH = DATA_WIDTH;
tdl_da_lc Utdldalc1n (.clk(clk), .clk_en(rdy_int & clk_en),.rst(rst),.data_in(tdl_0_n), .data_out(tdl_1_n) );
defparam Utdldalc1n.WIDTH = DATA_WIDTH;
tdl_da_lc Utdldalc2n (.clk(clk), .clk_en(rdy_int & clk_en),.rst(rst),.data_in(tdl_1_n), .data_out(tdl_2_n) );
defparam Utdldalc2n.WIDTH = DATA_WIDTH;
tdl_da_lc Utdldalc3n (.clk(clk), .clk_en(rdy_int & clk_en),.rst(rst),.data_in(tdl_2_n), .data_out(tdl_3_n) );
defparam Utdldalc3n.WIDTH = DATA_WIDTH;
tdl_da_lc Utdldalc4n (.clk(clk), .clk_en(rdy_int & clk_en),.rst(rst),.data_in(tdl_3_n), .data_out(tdl_4_n) );
defparam Utdldalc4n.WIDTH = DATA_WIDTH;
tdl_da_lc Utdldalc5n (.clk(clk), .clk_en(rdy_int & clk_en),.rst(rst),.data_in(tdl_4_n), .data_out(tdl_5_n) );
defparam Utdldalc5n.WIDTH = DATA_WIDTH;
tdl_da_lc Utdldalc6n (.clk(clk), .clk_en(rdy_int & clk_en),.rst(rst),.data_in(tdl_5_n), .data_out(tdl_6_n) );
defparam Utdldalc6n.WIDTH = DATA_WIDTH;
tdl_da_lc Utdldalc7n (.clk(clk), .clk_en(rdy_int & clk_en),.rst(rst),.data_in(tdl_6_n), .data_out(tdl_7_n) );
defparam Utdldalc7n.WIDTH = DATA_WIDTH;
tdl_da_lc Utdldalc8n (.clk(clk), .clk_en(rdy_int & clk_en),.rst(rst),.data_in(tdl_7_n), .data_out(tdl_8_n) );
defparam Utdldalc8n.WIDTH = DATA_WIDTH;
tdl_da_lc Utdldalc9n (.clk(clk), .clk_en(rdy_int & clk_en),.rst(rst),.data_in(tdl_8_n), .data_out(tdl_9_n) );
defparam Utdldalc9n.WIDTH = DATA_WIDTH;
tdl_da_lc Utdldalc10n (.clk(clk), .clk_en(rdy_int & clk_en),.rst(rst),.data_in(tdl_9_n), .data_out(tdl_10_n) );
defparam Utdldalc10n.WIDTH = DATA_WIDTH;
tdl_da_lc Utdldalc11n (.clk(clk), .clk_en(rdy_int & clk_en),.rst(rst),.data_in(tdl_10_n), .data_out(tdl_11_n) );
defparam Utdldalc11n.WIDTH = DATA_WIDTH;
tdl_da_lc Utdldalc12n (.clk(clk), .clk_en(rdy_int & clk_en),.rst(rst),.data_in(tdl_11_n), .data_out(tdl_12_n) );
defparam Utdldalc12n.WIDTH = DATA_WIDTH;
tdl_da_lc Utdldalc13n (.clk(clk), .clk_en(rdy_int & clk_en),.rst(rst),.data_in(tdl_12_n), .data_out(tdl_13_n) );
defparam Utdldalc13n.WIDTH = DATA_WIDTH;
tdl_da_lc Utdldalc14n (.clk(clk), .clk_en(rdy_int & clk_en),.rst(rst),.data_in(tdl_13_n), .data_out(tdl_14_n) );
defparam Utdldalc14n.WIDTH = DATA_WIDTH;
tdl_da_lc Utdldalc15n (.clk(clk), .clk_en(rdy_int & clk_en),.rst(rst),.data_in(tdl_14_n), .data_out(tdl_15_n) );
defparam Utdldalc15n.WIDTH = DATA_WIDTH;


// --- ROM LUTs ---- 
// symmetrical adders ...
wire [8:0] sym_res_0_n;
sadd_cen U_0_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_0_n), .bin(tdl_15_n), .res(sym_res_0_n) );
defparam U_0_sym_add.IN_WIDTH = 8;
defparam U_0_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_1_n;
sadd_cen U_1_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_1_n), .bin(tdl_14_n), .res(sym_res_1_n) );
defparam U_1_sym_add.IN_WIDTH = 8;
defparam U_1_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_2_n;
sadd_cen U_2_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_2_n), .bin(tdl_13_n), .res(sym_res_2_n) );
defparam U_2_sym_add.IN_WIDTH = 8;
defparam U_2_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_3_n;
sadd_cen U_3_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_3_n), .bin(tdl_12_n), .res(sym_res_3_n) );
defparam U_3_sym_add.IN_WIDTH = 8;
defparam U_3_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_4_n;
sadd_cen U_4_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_4_n), .bin(tdl_11_n), .res(sym_res_4_n) );
defparam U_4_sym_add.IN_WIDTH = 8;
defparam U_4_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_5_n;
sadd_cen U_5_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_5_n), .bin(tdl_10_n), .res(sym_res_5_n) );
defparam U_5_sym_add.IN_WIDTH = 8;
defparam U_5_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_6_n;
sadd_cen U_6_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_6_n), .bin(tdl_9_n), .res(sym_res_6_n) );
defparam U_6_sym_add.IN_WIDTH = 8;
defparam U_6_sym_add.PIPE_DEPTH = 1;
wire [8:0] sym_res_7_n;
sadd_cen U_7_sym_add (.clk(clk), .gclk_en(clk_en), .ain(tdl_7_n), .bin(tdl_8_n), .res(sym_res_7_n) );
defparam U_7_sym_add.IN_WIDTH = 8;
defparam U_7_sym_add.PIPE_DEPTH = 1;


wire [11:0] lut_val_0_n_0_pp;
rom_lut_r_cen Ur0_n_0_pp (.clk(clk),.gclk_en(clk_en),.addr_in( {sym_res_3_n[0],sym_res_2_n[0],sym_res_1_n[0],sym_res_0_n[0] } ), .data_out( lut_val_0_n_0_pp[8:0]) ) ;
 defparam Ur0_n_0_pp.DATA_WIDTH = 9;
defparam Ur0_n_0_pp.C0 = 9'd                   0;
defparam Ur0_n_0_pp.C1 = 9'd                   3;
defparam Ur0_n_0_pp.C2 = 9'd                  17;
defparam Ur0_n_0_pp.C3 = 9'd                  20;
defparam Ur0_n_0_pp.C4 = 9'd                  52;
defparam Ur0_n_0_pp.C5 = 9'd                  55;
defparam Ur0_n_0_pp.C6 = 9'd                  69;
defparam Ur0_n_0_pp.C7 = 9'd                  72;
defparam Ur0_n_0_pp.C8 = 9'd                 120;
defparam Ur0_n_0_pp.C9 = 9'd                 123;
defparam Ur0_n_0_pp.CA = 9'd                 137;
defparam Ur0_n_0_pp.CB = 9'd                 140;
defparam Ur0_n_0_pp.CC = 9'd                 172;
defparam Ur0_n_0_pp.CD = 9'd                 175;
defparam Ur0_n_0_pp.CE = 9'd                 189;
defparam Ur0_n_0_pp.CF = 9'd                 192;
assign lut_val_0_n_0_pp[11] = lut_val_0_n_0_pp[8];
assign lut_val_0_n_0_pp[10] = lut_val_0_n_0_pp[8];
assign lut_val_0_n_0_pp[9] = lut_val_0_n_0_pp[8];
wire [11:0] lut_val_0_n_1_pp;
rom_lut_r_cen Ur0_n_1_pp (.clk(clk),.gclk_en(clk_en),.addr_in( {sym_res_3_n[1],sym_res_2_n[1],sym_res_1_n[1],sym_res_0_n[1] } ), .data_out( lut_val_0_n_1_pp[8:0]) ) ;
 defparam Ur0_n_1_pp.DATA_WIDTH = 9;
defparam Ur0_n_1_pp.C0 = 9'd                   0;
defparam Ur0_n_1_pp.C1 = 9'd                   3;
defparam Ur0_n_1_pp.C2 = 9'd                  17;
defparam Ur0_n_1_pp.C3 = 9'd                  20;
defparam Ur0_n_1_pp.C4 = 9'd                  52;
defparam Ur0_n_1_pp.C5 = 9'd                  55;
defparam Ur0_n_1_pp.C6 = 9'd                  69;
defparam Ur0_n_1_pp.C7 = 9'd                  72;
defparam Ur0_n_1_pp.C8 = 9'd                 120;
defparam Ur0_n_1_pp.C9 = 9'd                 123;
defparam Ur0_n_1_pp.CA = 9'd                 137;
defparam Ur0_n_1_pp.CB = 9'd                 140;
defparam Ur0_n_1_pp.CC = 9'd                 172;
defparam Ur0_n_1_pp.CD = 9'd                 175;
defparam Ur0_n_1_pp.CE = 9'd                 189;
defparam Ur0_n_1_pp.CF = 9'd                 192;
assign lut_val_0_n_1_pp[11] = lut_val_0_n_1_pp[8];
assign lut_val_0_n_1_pp[10] = lut_val_0_n_1_pp[8];
assign lut_val_0_n_1_pp[9] = lut_val_0_n_1_pp[8];
wire [11:0] lut_val_0_n_2_pp;
rom_lut_r_cen Ur0_n_2_pp (.clk(clk),.gclk_en(clk_en),.addr_in( {sym_res_3_n[2],sym_res_2_n[2],sym_res_1_n[2],sym_res_0_n[2] } ), .data_out( lut_val_0_n_2_pp[8:0]) ) ;
 defparam Ur0_n_2_pp.DATA_WIDTH = 9;
defparam Ur0_n_2_pp.C0 = 9'd                   0;
defparam Ur0_n_2_pp.C1 = 9'd                   3;
defparam Ur0_n_2_pp.C2 = 9'd                  17;
defparam Ur0_n_2_pp.C3 = 9'd                  20;
defparam Ur0_n_2_pp.C4 = 9'd                  52;
defparam Ur0_n_2_pp.C5 = 9'd                  55;
defparam Ur0_n_2_pp.C6 = 9'd                  69;
defparam Ur0_n_2_pp.C7 = 9'd                  72;
defparam Ur0_n_2_pp.C8 = 9'd                 120;
defparam Ur0_n_2_pp.C9 = 9'd                 123;
defparam Ur0_n_2_pp.CA = 9'd                 137;
defparam Ur0_n_2_pp.CB = 9'd                 140;
defparam Ur0_n_2_pp.CC = 9'd                 172;
defparam Ur0_n_2_pp.CD = 9'd                 175;
defparam Ur0_n_2_pp.CE = 9'd                 189;
defparam Ur0_n_2_pp.CF = 9'd                 192;
assign lut_val_0_n_2_pp[11] = lut_val_0_n_2_pp[8];
assign lut_val_0_n_2_pp[10] = lut_val_0_n_2_pp[8];
assign lut_val_0_n_2_pp[9] = lut_val_0_n_2_pp[8];
wire [11:0] lut_val_0_n_3_pp;
rom_lut_r_cen Ur0_n_3_pp (.clk(clk),.gclk_en(clk_en),.addr_in( {sym_res_3_n[3],sym_res_2_n[3],sym_res_1_n[3],sym_res_0_n[3] } ), .data_out( lut_val_0_n_3_pp[8:0]) ) ;
 defparam Ur0_n_3_pp.DATA_WIDTH = 9;
defparam Ur0_n_3_pp.C0 = 9'd                   0;
defparam Ur0_n_3_pp.C1 = 9'd                   3;
defparam Ur0_n_3_pp.C2 = 9'd                  17;
defparam Ur0_n_3_pp.C3 = 9'd                  20;
defparam Ur0_n_3_pp.C4 = 9'd                  52;
defparam Ur0_n_3_pp.C5 = 9'd                  55;
defparam Ur0_n_3_pp.C6 = 9'd                  69;
defparam Ur0_n_3_pp.C7 = 9'd                  72;
defparam Ur0_n_3_pp.C8 = 9'd                 120;
defparam Ur0_n_3_pp.C9 = 9'd                 123;
defparam Ur0_n_3_pp.CA = 9'd                 137;
defparam Ur0_n_3_pp.CB = 9'd                 140;
defparam Ur0_n_3_pp.CC = 9'd                 172;
defparam Ur0_n_3_pp.CD = 9'd                 175;
defparam Ur0_n_3_pp.CE = 9'd                 189;
defparam Ur0_n_3_pp.CF = 9'd                 192;
assign lut_val_0_n_3_pp[11] = lut_val_0_n_3_pp[8];
assign lut_val_0_n_3_pp[10] = lut_val_0_n_3_pp[8];
assign lut_val_0_n_3_pp[9] = lut_val_0_n_3_pp[8];
wire [11:0] lut_val_0_n_4_pp;
rom_lut_r_cen Ur0_n_4_pp (.clk(clk),.gclk_en(clk_en),.addr_in( {sym_res_3_n[4],sym_res_2_n[4],sym_res_1_n[4],sym_res_0_n[4] } ), .data_out( lut_val_0_n_4_pp[8:0]) ) ;
 defparam Ur0_n_4_pp.DATA_WIDTH = 9;
defparam Ur0_n_4_pp.C0 = 9'd                   0;
defparam Ur0_n_4_pp.C1 = 9'd                   3;
defparam Ur0_n_4_pp.C2 = 9'd                  17;
defparam Ur0_n_4_pp.C3 = 9'd                  20;
defparam Ur0_n_4_pp.C4 = 9'd                  52;
defparam Ur0_n_4_pp.C5 = 9'd                  55;
defparam Ur0_n_4_pp.C6 = 9'd                  69;
defparam Ur0_n_4_pp.C7 = 9'd                  72;
defparam Ur0_n_4_pp.C8 = 9'd                 120;
defparam Ur0_n_4_pp.C9 = 9'd                 123;
defparam Ur0_n_4_pp.CA = 9'd                 137;
defparam Ur0_n_4_pp.CB = 9'd                 140;
defparam Ur0_n_4_pp.CC = 9'd                 172;
defparam Ur0_n_4_pp.CD = 9'd                 175;
defparam Ur0_n_4_pp.CE = 9'd                 189;
defparam Ur0_n_4_pp.CF = 9'd                 192;
assign lut_val_0_n_4_pp[11] = lut_val_0_n_4_pp[8];
assign lut_val_0_n_4_pp[10] = lut_val_0_n_4_pp[8];
assign lut_val_0_n_4_pp[9] = lut_val_0_n_4_pp[8];
wire [11:0] lut_val_0_n_5_pp;
rom_lut_r_cen Ur0_n_5_pp (.clk(clk),.gclk_en(clk_en),.addr_in( {sym_res_3_n[5],sym_res_2_n[5],sym_res_1_n[5],sym_res_0_n[5] } ), .data_out( lut_val_0_n_5_pp[8:0]) ) ;
 defparam Ur0_n_5_pp.DATA_WIDTH = 9;
defparam Ur0_n_5_pp.C0 = 9'd                   0;
defparam Ur0_n_5_pp.C1 = 9'd                   3;
defparam Ur0_n_5_pp.C2 = 9'd                  17;
defparam Ur0_n_5_pp.C3 = 9'd                  20;
defparam Ur0_n_5_pp.C4 = 9'd                  52;
defparam Ur0_n_5_pp.C5 = 9'd                  55;
defparam Ur0_n_5_pp.C6 = 9'd                  69;
defparam Ur0_n_5_pp.C7 = 9'd                  72;
defparam Ur0_n_5_pp.C8 = 9'd                 120;
defparam Ur0_n_5_pp.C9 = 9'd                 123;
defparam Ur0_n_5_pp.CA = 9'd                 137;
defparam Ur0_n_5_pp.CB = 9'd                 140;
defparam Ur0_n_5_pp.CC = 9'd                 172;
defparam Ur0_n_5_pp.CD = 9'd                 175;
defparam Ur0_n_5_pp.CE = 9'd                 189;
defparam Ur0_n_5_pp.CF = 9'd                 192;
assign lut_val_0_n_5_pp[11] = lut_val_0_n_5_pp[8];
assign lut_val_0_n_5_pp[10] = lut_val_0_n_5_pp[8];
assign lut_val_0_n_5_pp[9] = lut_val_0_n_5_pp[8];
wire [11:0] lut_val_0_n_6_pp;
rom_lut_r_cen Ur0_n_6_pp (.clk(clk),.gclk_en(clk_en),.addr_in( {sym_res_3_n[6],sym_res_2_n[6],sym_res_1_n[6],sym_res_0_n[6] } ), .data_out( lut_val_0_n_6_pp[8:0]) ) ;
 defparam Ur0_n_6_pp.DATA_WIDTH = 9;
defparam Ur0_n_6_pp.C0 = 9'd                   0;
defparam Ur0_n_6_pp.C1 = 9'd                   3;
defparam Ur0_n_6_pp.C2 = 9'd                  17;
defparam Ur0_n_6_pp.C3 = 9'd                  20;
defparam Ur0_n_6_pp.C4 = 9'd                  52;
defparam Ur0_n_6_pp.C5 = 9'd                  55;
defparam Ur0_n_6_pp.C6 = 9'd                  69;
defparam Ur0_n_6_pp.C7 = 9'd                  72;
defparam Ur0_n_6_pp.C8 = 9'd                 120;
defparam Ur0_n_6_pp.C9 = 9'd                 123;
defparam Ur0_n_6_pp.CA = 9'd                 137;
defparam Ur0_n_6_pp.CB = 9'd                 140;
defparam Ur0_n_6_pp.CC = 9'd                 172;
defparam Ur0_n_6_pp.CD = 9'd                 175;
defparam Ur0_n_6_pp.CE = 9'd                 189;
defparam Ur0_n_6_pp.CF = 9'd                 192;
assign lut_val_0_n_6_pp[11] = lut_val_0_n_6_pp[8];
assign lut_val_0_n_6_pp[10] = lut_val_0_n_6_pp[8];
assign lut_val_0_n_6_pp[9] = lut_val_0_n_6_pp[8];
wire [11:0] lut_val_0_n_7_pp;
rom_lut_r_cen Ur0_n_7_pp (.clk(clk),.gclk_en(clk_en),.addr_in( {sym_res_3_n[7],sym_res_2_n[7],sym_res_1_n[7],sym_res_0_n[7] } ), .data_out( lut_val_0_n_7_pp[8:0]) ) ;
 defparam Ur0_n_7_pp.DATA_WIDTH = 9;
defparam Ur0_n_7_pp.C0 = 9'd                   0;
defparam Ur0_n_7_pp.C1 = 9'd                   3;
defparam Ur0_n_7_pp.C2 = 9'd                  17;
defparam Ur0_n_7_pp.C3 = 9'd                  20;
defparam Ur0_n_7_pp.C4 = 9'd                  52;
defparam Ur0_n_7_pp.C5 = 9'd                  55;
defparam Ur0_n_7_pp.C6 = 9'd                  69;
defparam Ur0_n_7_pp.C7 = 9'd                  72;
defparam Ur0_n_7_pp.C8 = 9'd                 120;
defparam Ur0_n_7_pp.C9 = 9'd                 123;
defparam Ur0_n_7_pp.CA = 9'd                 137;
defparam Ur0_n_7_pp.CB = 9'd                 140;
defparam Ur0_n_7_pp.CC = 9'd                 172;
defparam Ur0_n_7_pp.CD = 9'd                 175;
defparam Ur0_n_7_pp.CE = 9'd                 189;
defparam Ur0_n_7_pp.CF = 9'd                 192;
assign lut_val_0_n_7_pp[11] = lut_val_0_n_7_pp[8];
assign lut_val_0_n_7_pp[10] = lut_val_0_n_7_pp[8];
assign lut_val_0_n_7_pp[9] = lut_val_0_n_7_pp[8];
wire [11:0] lut_val_0_n_8_pp;
rom_lut_r_cen Ur0_n_8_pp (.clk(clk),.gclk_en(clk_en),.addr_in( {sym_res_3_n[8],sym_res_2_n[8],sym_res_1_n[8],sym_res_0_n[8] } ), .data_out( lut_val_0_n_8_pp[8:0]) ) ;
 defparam Ur0_n_8_pp.DATA_WIDTH = 9;
defparam Ur0_n_8_pp.C0 = 9'd                   0;
defparam Ur0_n_8_pp.C1 = 9'd                 509;
defparam Ur0_n_8_pp.C2 = 9'd                 495;
defparam Ur0_n_8_pp.C3 = 9'd                 492;
defparam Ur0_n_8_pp.C4 = 9'd                 460;
defparam Ur0_n_8_pp.C5 = 9'd                 457;
defparam Ur0_n_8_pp.C6 = 9'd                 443;
defparam Ur0_n_8_pp.C7 = 9'd                 440;
defparam Ur0_n_8_pp.C8 = 9'd                 392;
defparam Ur0_n_8_pp.C9 = 9'd                 389;
defparam Ur0_n_8_pp.CA = 9'd                 375;
defparam Ur0_n_8_pp.CB = 9'd                 372;
defparam Ur0_n_8_pp.CC = 9'd                 340;
defparam Ur0_n_8_pp.CD = 9'd                 337;
defparam Ur0_n_8_pp.CE = 9'd                 323;
defparam Ur0_n_8_pp.CF = 9'd                 320;
assign lut_val_0_n_8_pp[11] = lut_val_0_n_8_pp[8];
assign lut_val_0_n_8_pp[10] = lut_val_0_n_8_pp[8];
assign lut_val_0_n_8_pp[9] = lut_val_0_n_8_pp[8];
wire [11:0] lut_val_1_n_0_pp;
rom_lut_r_cen Ur1_n_0_pp (.clk(clk),.gclk_en(clk_en),.addr_in( {sym_res_7_n[0],sym_res_6_n[0],sym_res_5_n[0],sym_res_4_n[0] } ), .data_out( lut_val_1_n_0_pp[11:0]) ) ;
 defparam Ur1_n_0_pp.DATA_WIDTH = 12;
defparam Ur1_n_0_pp.C0 = 12'd                   0;
defparam Ur1_n_0_pp.C1 = 12'd                 220;
defparam Ur1_n_0_pp.C2 = 12'd                 338;
defparam Ur1_n_0_pp.C3 = 12'd                 558;
defparam Ur1_n_0_pp.C4 = 12'd                 446;
defparam Ur1_n_0_pp.C5 = 12'd                 666;
defparam Ur1_n_0_pp.C6 = 12'd                 784;
defparam Ur1_n_0_pp.C7 = 12'd                1004;
defparam Ur1_n_0_pp.C8 = 12'd                 511;
defparam Ur1_n_0_pp.C9 = 12'd                 731;
defparam Ur1_n_0_pp.CA = 12'd                 849;
defparam Ur1_n_0_pp.CB = 12'd                1069;
defparam Ur1_n_0_pp.CC = 12'd                 957;
defparam Ur1_n_0_pp.CD = 12'd                1177;
defparam Ur1_n_0_pp.CE = 12'd                1295;
defparam Ur1_n_0_pp.CF = 12'd                1515;
wire [11:0] lut_val_1_n_1_pp;
rom_lut_r_cen Ur1_n_1_pp (.clk(clk),.gclk_en(clk_en),.addr_in( {sym_res_7_n[1],sym_res_6_n[1],sym_res_5_n[1],sym_res_4_n[1] } ), .data_out( lut_val_1_n_1_pp[11:0]) ) ;
 defparam Ur1_n_1_pp.DATA_WIDTH = 12;
defparam Ur1_n_1_pp.C0 = 12'd                   0;
defparam Ur1_n_1_pp.C1 = 12'd                 220;
defparam Ur1_n_1_pp.C2 = 12'd                 338;
defparam Ur1_n_1_pp.C3 = 12'd                 558;
defparam Ur1_n_1_pp.C4 = 12'd                 446;
defparam Ur1_n_1_pp.C5 = 12'd                 666;
defparam Ur1_n_1_pp.C6 = 12'd                 784;
defparam Ur1_n_1_pp.C7 = 12'd                1004;
defparam Ur1_n_1_pp.C8 = 12'd                 511;
defparam Ur1_n_1_pp.C9 = 12'd                 731;
defparam Ur1_n_1_pp.CA = 12'd                 849;
defparam Ur1_n_1_pp.CB = 12'd                1069;
defparam Ur1_n_1_pp.CC = 12'd                 957;
defparam Ur1_n_1_pp.CD = 12'd                1177;
defparam Ur1_n_1_pp.CE = 12'd                1295;
defparam Ur1_n_1_pp.CF = 12'd                1515;
wire [11:0] lut_val_1_n_2_pp;
rom_lut_r_cen Ur1_n_2_pp (.clk(clk),.gclk_en(clk_en),.addr_in( {sym_res_7_n[2],sym_res_6_n[2],sym_res_5_n[2],sym_res_4_n[2] } ), .data_out( lut_val_1_n_2_pp[11:0]) ) ;
 defparam Ur1_n_2_pp.DATA_WIDTH = 12;
defparam Ur1_n_2_pp.C0 = 12'd                   0;
defparam Ur1_n_2_pp.C1 = 12'd                 220;
defparam Ur1_n_2_pp.C2 = 12'd                 338;
defparam Ur1_n_2_pp.C3 = 12'd                 558;
defparam Ur1_n_2_pp.C4 = 12'd                 446;
defparam Ur1_n_2_pp.C5 = 12'd                 666;
defparam Ur1_n_2_pp.C6 = 12'd                 784;
defparam Ur1_n_2_pp.C7 = 12'd                1004;
defparam Ur1_n_2_pp.C8 = 12'd                 511;
defparam Ur1_n_2_pp.C9 = 12'd                 731;
defparam Ur1_n_2_pp.CA = 12'd                 849;
defparam Ur1_n_2_pp.CB = 12'd                1069;
defparam Ur1_n_2_pp.CC = 12'd                 957;
defparam Ur1_n_2_pp.CD = 12'd                1177;
defparam Ur1_n_2_pp.CE = 12'd                1295;
defparam Ur1_n_2_pp.CF = 12'd                1515;
wire [11:0] lut_val_1_n_3_pp;
rom_lut_r_cen Ur1_n_3_pp (.clk(clk),.gclk_en(clk_en),.addr_in( {sym_res_7_n[3],sym_res_6_n[3],sym_res_5_n[3],sym_res_4_n[3] } ), .data_out( lut_val_1_n_3_pp[11:0]) ) ;
 defparam Ur1_n_3_pp.DATA_WIDTH = 12;
defparam Ur1_n_3_pp.C0 = 12'd                   0;
defparam Ur1_n_3_pp.C1 = 12'd                 220;
defparam Ur1_n_3_pp.C2 = 12'd                 338;
defparam Ur1_n_3_pp.C3 = 12'd                 558;
defparam Ur1_n_3_pp.C4 = 12'd                 446;
defparam Ur1_n_3_pp.C5 = 12'd                 666;
defparam Ur1_n_3_pp.C6 = 12'd                 784;
defparam Ur1_n_3_pp.C7 = 12'd                1004;
defparam Ur1_n_3_pp.C8 = 12'd                 511;
defparam Ur1_n_3_pp.C9 = 12'd                 731;
defparam Ur1_n_3_pp.CA = 12'd                 849;
defparam Ur1_n_3_pp.CB = 12'd                1069;
defparam Ur1_n_3_pp.CC = 12'd                 957;
defparam Ur1_n_3_pp.CD = 12'd                1177;
defparam Ur1_n_3_pp.CE = 12'd                1295;
defparam Ur1_n_3_pp.CF = 12'd                1515;
wire [11:0] lut_val_1_n_4_pp;
rom_lut_r_cen Ur1_n_4_pp (.clk(clk),.gclk_en(clk_en),.addr_in( {sym_res_7_n[4],sym_res_6_n[4],sym_res_5_n[4],sym_res_4_n[4] } ), .data_out( lut_val_1_n_4_pp[11:0]) ) ;
 defparam Ur1_n_4_pp.DATA_WIDTH = 12;
defparam Ur1_n_4_pp.C0 = 12'd                   0;
defparam Ur1_n_4_pp.C1 = 12'd                 220;
defparam Ur1_n_4_pp.C2 = 12'd                 338;
defparam Ur1_n_4_pp.C3 = 12'd                 558;
defparam Ur1_n_4_pp.C4 = 12'd                 446;
defparam Ur1_n_4_pp.C5 = 12'd                 666;
defparam Ur1_n_4_pp.C6 = 12'd                 784;
defparam Ur1_n_4_pp.C7 = 12'd                1004;
defparam Ur1_n_4_pp.C8 = 12'd                 511;
defparam Ur1_n_4_pp.C9 = 12'd                 731;
defparam Ur1_n_4_pp.CA = 12'd                 849;
defparam Ur1_n_4_pp.CB = 12'd                1069;
defparam Ur1_n_4_pp.CC = 12'd                 957;
defparam Ur1_n_4_pp.CD = 12'd                1177;
defparam Ur1_n_4_pp.CE = 12'd                1295;
defparam Ur1_n_4_pp.CF = 12'd                1515;
wire [11:0] lut_val_1_n_5_pp;
rom_lut_r_cen Ur1_n_5_pp (.clk(clk),.gclk_en(clk_en),.addr_in( {sym_res_7_n[5],sym_res_6_n[5],sym_res_5_n[5],sym_res_4_n[5] } ), .data_out( lut_val_1_n_5_pp[11:0]) ) ;
 defparam Ur1_n_5_pp.DATA_WIDTH = 12;
defparam Ur1_n_5_pp.C0 = 12'd                   0;
defparam Ur1_n_5_pp.C1 = 12'd                 220;
defparam Ur1_n_5_pp.C2 = 12'd                 338;
defparam Ur1_n_5_pp.C3 = 12'd                 558;
defparam Ur1_n_5_pp.C4 = 12'd                 446;
defparam Ur1_n_5_pp.C5 = 12'd                 666;
defparam Ur1_n_5_pp.C6 = 12'd                 784;
defparam Ur1_n_5_pp.C7 = 12'd                1004;
defparam Ur1_n_5_pp.C8 = 12'd                 511;
defparam Ur1_n_5_pp.C9 = 12'd                 731;
defparam Ur1_n_5_pp.CA = 12'd                 849;
defparam Ur1_n_5_pp.CB = 12'd                1069;
defparam Ur1_n_5_pp.CC = 12'd                 957;
defparam Ur1_n_5_pp.CD = 12'd                1177;
defparam Ur1_n_5_pp.CE = 12'd                1295;
defparam Ur1_n_5_pp.CF = 12'd                1515;
wire [11:0] lut_val_1_n_6_pp;
rom_lut_r_cen Ur1_n_6_pp (.clk(clk),.gclk_en(clk_en),.addr_in( {sym_res_7_n[6],sym_res_6_n[6],sym_res_5_n[6],sym_res_4_n[6] } ), .data_out( lut_val_1_n_6_pp[11:0]) ) ;
 defparam Ur1_n_6_pp.DATA_WIDTH = 12;
defparam Ur1_n_6_pp.C0 = 12'd                   0;
defparam Ur1_n_6_pp.C1 = 12'd                 220;
defparam Ur1_n_6_pp.C2 = 12'd                 338;
defparam Ur1_n_6_pp.C3 = 12'd                 558;
defparam Ur1_n_6_pp.C4 = 12'd                 446;
defparam Ur1_n_6_pp.C5 = 12'd                 666;
defparam Ur1_n_6_pp.C6 = 12'd                 784;
defparam Ur1_n_6_pp.C7 = 12'd                1004;
defparam Ur1_n_6_pp.C8 = 12'd                 511;
defparam Ur1_n_6_pp.C9 = 12'd                 731;
defparam Ur1_n_6_pp.CA = 12'd                 849;
defparam Ur1_n_6_pp.CB = 12'd                1069;
defparam Ur1_n_6_pp.CC = 12'd                 957;
defparam Ur1_n_6_pp.CD = 12'd                1177;
defparam Ur1_n_6_pp.CE = 12'd                1295;
defparam Ur1_n_6_pp.CF = 12'd                1515;
wire [11:0] lut_val_1_n_7_pp;
rom_lut_r_cen Ur1_n_7_pp (.clk(clk),.gclk_en(clk_en),.addr_in( {sym_res_7_n[7],sym_res_6_n[7],sym_res_5_n[7],sym_res_4_n[7] } ), .data_out( lut_val_1_n_7_pp[11:0]) ) ;
 defparam Ur1_n_7_pp.DATA_WIDTH = 12;
defparam Ur1_n_7_pp.C0 = 12'd                   0;
defparam Ur1_n_7_pp.C1 = 12'd                 220;
defparam Ur1_n_7_pp.C2 = 12'd                 338;
defparam Ur1_n_7_pp.C3 = 12'd                 558;
defparam Ur1_n_7_pp.C4 = 12'd                 446;
defparam Ur1_n_7_pp.C5 = 12'd                 666;
defparam Ur1_n_7_pp.C6 = 12'd                 784;
defparam Ur1_n_7_pp.C7 = 12'd                1004;
defparam Ur1_n_7_pp.C8 = 12'd                 511;
defparam Ur1_n_7_pp.C9 = 12'd                 731;
defparam Ur1_n_7_pp.CA = 12'd                 849;
defparam Ur1_n_7_pp.CB = 12'd                1069;
defparam Ur1_n_7_pp.CC = 12'd                 957;
defparam Ur1_n_7_pp.CD = 12'd                1177;
defparam Ur1_n_7_pp.CE = 12'd                1295;
defparam Ur1_n_7_pp.CF = 12'd                1515;
wire [11:0] lut_val_1_n_8_pp;
rom_lut_r_cen Ur1_n_8_pp (.clk(clk),.gclk_en(clk_en),.addr_in( {sym_res_7_n[8],sym_res_6_n[8],sym_res_5_n[8],sym_res_4_n[8] } ), .data_out( lut_val_1_n_8_pp[11:0]) ) ;
 defparam Ur1_n_8_pp.DATA_WIDTH = 12;
defparam Ur1_n_8_pp.C0 = 12'd                   0;
defparam Ur1_n_8_pp.C1 = 12'd                3876;
defparam Ur1_n_8_pp.C2 = 12'd                3758;
defparam Ur1_n_8_pp.C3 = 12'd                3538;
defparam Ur1_n_8_pp.C4 = 12'd                3650;
defparam Ur1_n_8_pp.C5 = 12'd                3430;
defparam Ur1_n_8_pp.C6 = 12'd                3312;
defparam Ur1_n_8_pp.C7 = 12'd                3092;
defparam Ur1_n_8_pp.C8 = 12'd                3585;
defparam Ur1_n_8_pp.C9 = 12'd                3365;
defparam Ur1_n_8_pp.CA = 12'd                3247;
defparam Ur1_n_8_pp.CB = 12'd                3027;
defparam Ur1_n_8_pp.CC = 12'd                3139;
defparam Ur1_n_8_pp.CD = 12'd                2919;
defparam Ur1_n_8_pp.CE = 12'd                2801;
defparam Ur1_n_8_pp.CF = 12'd                2581;


// ---- partial product adder tree ----

wire [19:0] lut_0_bit_0_fill;
wire [19:0] lut_0_bit_1_fill;
wire [19:0] lut_0_bit_2_fill;
wire [19:0] lut_0_bit_3_fill;
wire [19:0] lut_0_bit_4_fill;
wire [19:0] lut_0_bit_5_fill;
wire [19:0] lut_0_bit_6_fill;
wire [19:0] lut_0_bit_7_fill;
wire [19:0] lut_0_bit_8_fill;
assign lut_0_bit_0_fill = {lut_val_0_n_0_pp[11], lut_val_0_n_0_pp[11], lut_val_0_n_0_pp[11], lut_val_0_n_0_pp[11], lut_val_0_n_0_pp[11], lut_val_0_n_0_pp[11], lut_val_0_n_0_pp[11], lut_val_0_n_0_pp[11],  lut_val_0_n_0_pp };
assign lut_0_bit_1_fill = {lut_val_0_n_1_pp[11], lut_val_0_n_1_pp[11], lut_val_0_n_1_pp[11], lut_val_0_n_1_pp[11], lut_val_0_n_1_pp[11], lut_val_0_n_1_pp[11], lut_val_0_n_1_pp[11],  lut_val_0_n_1_pp, 1'd0 };
assign lut_0_bit_2_fill = {lut_val_0_n_2_pp[11], lut_val_0_n_2_pp[11], lut_val_0_n_2_pp[11], lut_val_0_n_2_pp[11], lut_val_0_n_2_pp[11], lut_val_0_n_2_pp[11],  lut_val_0_n_2_pp, 2'd0 };
assign lut_0_bit_3_fill = {lut_val_0_n_3_pp[11], lut_val_0_n_3_pp[11], lut_val_0_n_3_pp[11], lut_val_0_n_3_pp[11], lut_val_0_n_3_pp[11],  lut_val_0_n_3_pp, 3'd0 };
assign lut_0_bit_4_fill = {lut_val_0_n_4_pp[11], lut_val_0_n_4_pp[11], lut_val_0_n_4_pp[11], lut_val_0_n_4_pp[11],  lut_val_0_n_4_pp, 4'd0 };
assign lut_0_bit_5_fill = {lut_val_0_n_5_pp[11], lut_val_0_n_5_pp[11], lut_val_0_n_5_pp[11],  lut_val_0_n_5_pp, 5'd0 };
assign lut_0_bit_6_fill = {lut_val_0_n_6_pp[11], lut_val_0_n_6_pp[11],  lut_val_0_n_6_pp, 6'd0 };
assign lut_0_bit_7_fill = {lut_val_0_n_7_pp[11],  lut_val_0_n_7_pp, 7'd0 };
assign lut_0_bit_8_fill = { lut_val_0_n_8_pp, 8'd0 };
wire [20:0] tree_0_pp_l_0_n_0_n;
sadd_lpm_cen Uadd_0_lut_l_0_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(lut_0_bit_0_fill), .bin(lut_0_bit_1_fill), .res(tree_0_pp_l_0_n_0_n) );
defparam Uadd_0_lut_l_0_n_0_n.IN_WIDTH = 20;
defparam Uadd_0_lut_l_0_n_0_n.PIPE_DEPTH = 1;
wire [20:0] tree_0_pp_l_0_n_1_n;
sadd_lpm_cen Uadd_0_lut_l_0_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(lut_0_bit_2_fill), .bin(lut_0_bit_3_fill), .res(tree_0_pp_l_0_n_1_n) );
defparam Uadd_0_lut_l_0_n_1_n.IN_WIDTH = 20;
defparam Uadd_0_lut_l_0_n_1_n.PIPE_DEPTH = 1;
wire [20:0] tree_0_pp_l_0_n_2_n;
sadd_lpm_cen Uadd_0_lut_l_0_n_2_n (.clk(clk),  .gclk_en(clk_en), .ain(lut_0_bit_4_fill), .bin(lut_0_bit_5_fill), .res(tree_0_pp_l_0_n_2_n) );
defparam Uadd_0_lut_l_0_n_2_n.IN_WIDTH = 20;
defparam Uadd_0_lut_l_0_n_2_n.PIPE_DEPTH = 1;
wire [20:0] tree_0_pp_l_0_n_3_n;
sadd_lpm_cen Uadd_0_lut_l_0_n_3_n (.clk(clk),  .gclk_en(clk_en), .ain(lut_0_bit_6_fill), .bin(lut_0_bit_7_fill), .res(tree_0_pp_l_0_n_3_n) );
defparam Uadd_0_lut_l_0_n_3_n.IN_WIDTH = 20;
defparam Uadd_0_lut_l_0_n_3_n.PIPE_DEPTH = 1;
wire [20:0] tree_0_pp_l_0_n_4_n;
sadd_lpm_cen Uadd_0_lut_l_0_n_4_n (.clk(clk),  .gclk_en(clk_en), .ain(lut_0_bit_8_fill), .bin(20'd0), .res(tree_0_pp_l_0_n_4_n) );
defparam Uadd_0_lut_l_0_n_4_n.IN_WIDTH = 20;
defparam Uadd_0_lut_l_0_n_4_n.PIPE_DEPTH = 1;

wire [21:0] tree_0_pp_l_1_n_0_n;
sadd_lpm_cen Uadd_0_lut_l_1_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_0_pp_l_0_n_0_n), .bin(tree_0_pp_l_0_n_1_n), .res(tree_0_pp_l_1_n_0_n) );
defparam Uadd_0_lut_l_1_n_0_n.IN_WIDTH = 21;
defparam Uadd_0_lut_l_1_n_0_n.PIPE_DEPTH = 1;
wire [21:0] tree_0_pp_l_1_n_1_n;
sadd_lpm_cen Uadd_0_lut_l_1_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_0_pp_l_0_n_2_n), .bin(tree_0_pp_l_0_n_3_n), .res(tree_0_pp_l_1_n_1_n) );
defparam Uadd_0_lut_l_1_n_1_n.IN_WIDTH = 21;
defparam Uadd_0_lut_l_1_n_1_n.PIPE_DEPTH = 1;
wire [21:0] tree_0_pp_l_1_n_2_n;
sadd_lpm_cen Uadd_0_lut_l_1_n_2_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_0_pp_l_0_n_4_n), .bin(21'd0), .res(tree_0_pp_l_1_n_2_n) );
defparam Uadd_0_lut_l_1_n_2_n.IN_WIDTH = 21;
defparam Uadd_0_lut_l_1_n_2_n.PIPE_DEPTH = 1;

wire [22:0] tree_0_pp_l_2_n_0_n;
sadd_lpm_cen Uadd_0_lut_l_2_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_0_pp_l_1_n_0_n), .bin(tree_0_pp_l_1_n_1_n), .res(tree_0_pp_l_2_n_0_n) );
defparam Uadd_0_lut_l_2_n_0_n.IN_WIDTH = 22;
defparam Uadd_0_lut_l_2_n_0_n.PIPE_DEPTH = 1;
wire [22:0] tree_0_pp_l_2_n_1_n;
sadd_lpm_cen Uadd_0_lut_l_2_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_0_pp_l_1_n_2_n), .bin(22'd0), .res(tree_0_pp_l_2_n_1_n) );
defparam Uadd_0_lut_l_2_n_1_n.IN_WIDTH = 22;
defparam Uadd_0_lut_l_2_n_1_n.PIPE_DEPTH = 1;

wire [23:0] tree_0_pp_l_3_n_0_n;
sadd_lpm_cen Uadd_0_lut_l_3_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_0_pp_l_2_n_0_n), .bin(tree_0_pp_l_2_n_1_n), .res(tree_0_pp_l_3_n_0_n) );
defparam Uadd_0_lut_l_3_n_0_n.IN_WIDTH = 23;
defparam Uadd_0_lut_l_3_n_0_n.PIPE_DEPTH = 1;

wire [23:0] lut_val_0_n;
assign lut_val_0_n=tree_0_pp_l_3_n_0_n;


// ---- partial product adder tree ----

wire [19:0] lut_1_bit_0_fill;
wire [19:0] lut_1_bit_1_fill;
wire [19:0] lut_1_bit_2_fill;
wire [19:0] lut_1_bit_3_fill;
wire [19:0] lut_1_bit_4_fill;
wire [19:0] lut_1_bit_5_fill;
wire [19:0] lut_1_bit_6_fill;
wire [19:0] lut_1_bit_7_fill;
wire [19:0] lut_1_bit_8_fill;
assign lut_1_bit_0_fill = {lut_val_1_n_0_pp[11], lut_val_1_n_0_pp[11], lut_val_1_n_0_pp[11], lut_val_1_n_0_pp[11], lut_val_1_n_0_pp[11], lut_val_1_n_0_pp[11], lut_val_1_n_0_pp[11], lut_val_1_n_0_pp[11],  lut_val_1_n_0_pp };
assign lut_1_bit_1_fill = {lut_val_1_n_1_pp[11], lut_val_1_n_1_pp[11], lut_val_1_n_1_pp[11], lut_val_1_n_1_pp[11], lut_val_1_n_1_pp[11], lut_val_1_n_1_pp[11], lut_val_1_n_1_pp[11],  lut_val_1_n_1_pp, 1'd0 };
assign lut_1_bit_2_fill = {lut_val_1_n_2_pp[11], lut_val_1_n_2_pp[11], lut_val_1_n_2_pp[11], lut_val_1_n_2_pp[11], lut_val_1_n_2_pp[11], lut_val_1_n_2_pp[11],  lut_val_1_n_2_pp, 2'd0 };
assign lut_1_bit_3_fill = {lut_val_1_n_3_pp[11], lut_val_1_n_3_pp[11], lut_val_1_n_3_pp[11], lut_val_1_n_3_pp[11], lut_val_1_n_3_pp[11],  lut_val_1_n_3_pp, 3'd0 };
assign lut_1_bit_4_fill = {lut_val_1_n_4_pp[11], lut_val_1_n_4_pp[11], lut_val_1_n_4_pp[11], lut_val_1_n_4_pp[11],  lut_val_1_n_4_pp, 4'd0 };
assign lut_1_bit_5_fill = {lut_val_1_n_5_pp[11], lut_val_1_n_5_pp[11], lut_val_1_n_5_pp[11],  lut_val_1_n_5_pp, 5'd0 };
assign lut_1_bit_6_fill = {lut_val_1_n_6_pp[11], lut_val_1_n_6_pp[11],  lut_val_1_n_6_pp, 6'd0 };
assign lut_1_bit_7_fill = {lut_val_1_n_7_pp[11],  lut_val_1_n_7_pp, 7'd0 };
assign lut_1_bit_8_fill = { lut_val_1_n_8_pp, 8'd0 };
wire [20:0] tree_1_pp_l_0_n_0_n;
sadd_lpm_cen Uadd_1_lut_l_0_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(lut_1_bit_0_fill), .bin(lut_1_bit_1_fill), .res(tree_1_pp_l_0_n_0_n) );
defparam Uadd_1_lut_l_0_n_0_n.IN_WIDTH = 20;
defparam Uadd_1_lut_l_0_n_0_n.PIPE_DEPTH = 1;
wire [20:0] tree_1_pp_l_0_n_1_n;
sadd_lpm_cen Uadd_1_lut_l_0_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(lut_1_bit_2_fill), .bin(lut_1_bit_3_fill), .res(tree_1_pp_l_0_n_1_n) );
defparam Uadd_1_lut_l_0_n_1_n.IN_WIDTH = 20;
defparam Uadd_1_lut_l_0_n_1_n.PIPE_DEPTH = 1;
wire [20:0] tree_1_pp_l_0_n_2_n;
sadd_lpm_cen Uadd_1_lut_l_0_n_2_n (.clk(clk),  .gclk_en(clk_en), .ain(lut_1_bit_4_fill), .bin(lut_1_bit_5_fill), .res(tree_1_pp_l_0_n_2_n) );
defparam Uadd_1_lut_l_0_n_2_n.IN_WIDTH = 20;
defparam Uadd_1_lut_l_0_n_2_n.PIPE_DEPTH = 1;
wire [20:0] tree_1_pp_l_0_n_3_n;
sadd_lpm_cen Uadd_1_lut_l_0_n_3_n (.clk(clk),  .gclk_en(clk_en), .ain(lut_1_bit_6_fill), .bin(lut_1_bit_7_fill), .res(tree_1_pp_l_0_n_3_n) );
defparam Uadd_1_lut_l_0_n_3_n.IN_WIDTH = 20;
defparam Uadd_1_lut_l_0_n_3_n.PIPE_DEPTH = 1;
wire [20:0] tree_1_pp_l_0_n_4_n;
sadd_lpm_cen Uadd_1_lut_l_0_n_4_n (.clk(clk),  .gclk_en(clk_en), .ain(lut_1_bit_8_fill), .bin(20'd0), .res(tree_1_pp_l_0_n_4_n) );
defparam Uadd_1_lut_l_0_n_4_n.IN_WIDTH = 20;
defparam Uadd_1_lut_l_0_n_4_n.PIPE_DEPTH = 1;

wire [21:0] tree_1_pp_l_1_n_0_n;
sadd_lpm_cen Uadd_1_lut_l_1_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_1_pp_l_0_n_0_n), .bin(tree_1_pp_l_0_n_1_n), .res(tree_1_pp_l_1_n_0_n) );
defparam Uadd_1_lut_l_1_n_0_n.IN_WIDTH = 21;
defparam Uadd_1_lut_l_1_n_0_n.PIPE_DEPTH = 1;
wire [21:0] tree_1_pp_l_1_n_1_n;
sadd_lpm_cen Uadd_1_lut_l_1_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_1_pp_l_0_n_2_n), .bin(tree_1_pp_l_0_n_3_n), .res(tree_1_pp_l_1_n_1_n) );
defparam Uadd_1_lut_l_1_n_1_n.IN_WIDTH = 21;
defparam Uadd_1_lut_l_1_n_1_n.PIPE_DEPTH = 1;
wire [21:0] tree_1_pp_l_1_n_2_n;
sadd_lpm_cen Uadd_1_lut_l_1_n_2_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_1_pp_l_0_n_4_n), .bin(21'd0), .res(tree_1_pp_l_1_n_2_n) );
defparam Uadd_1_lut_l_1_n_2_n.IN_WIDTH = 21;
defparam Uadd_1_lut_l_1_n_2_n.PIPE_DEPTH = 1;

wire [22:0] tree_1_pp_l_2_n_0_n;
sadd_lpm_cen Uadd_1_lut_l_2_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_1_pp_l_1_n_0_n), .bin(tree_1_pp_l_1_n_1_n), .res(tree_1_pp_l_2_n_0_n) );
defparam Uadd_1_lut_l_2_n_0_n.IN_WIDTH = 22;
defparam Uadd_1_lut_l_2_n_0_n.PIPE_DEPTH = 1;
wire [22:0] tree_1_pp_l_2_n_1_n;
sadd_lpm_cen Uadd_1_lut_l_2_n_1_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_1_pp_l_1_n_2_n), .bin(22'd0), .res(tree_1_pp_l_2_n_1_n) );
defparam Uadd_1_lut_l_2_n_1_n.IN_WIDTH = 22;
defparam Uadd_1_lut_l_2_n_1_n.PIPE_DEPTH = 1;

wire [23:0] tree_1_pp_l_3_n_0_n;
sadd_lpm_cen Uadd_1_lut_l_3_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(tree_1_pp_l_2_n_0_n), .bin(tree_1_pp_l_2_n_1_n), .res(tree_1_pp_l_3_n_0_n) );
defparam Uadd_1_lut_l_3_n_0_n.IN_WIDTH = 23;
defparam Uadd_1_lut_l_3_n_0_n.PIPE_DEPTH = 1;

wire [23:0] lut_val_1_n;
assign lut_val_1_n=tree_1_pp_l_3_n_0_n;


// ---- final adder tree ----

wire [24:0] fin_atree_l_0_n_0_n;
sadd_lpm_cen Uadd_cen_l_0_n_0_n (.clk(clk),  .gclk_en(clk_en), .ain(lut_val_0_n), .bin(lut_val_1_n), .res(fin_atree_l_0_n_0_n) );
defparam Uadd_cen_l_0_n_0_n.IN_WIDTH = 24;
defparam Uadd_cen_l_0_n_0_n.PIPE_DEPTH = 1;

wire [24:0] mac_res;
assign mac_res=fin_atree_l_0_n_0_n;
wire [24:0] atree_res;
mac_tl Umtl (.clk(clk), 
             .data_in(mac_res),
             .data_out(atree_res));
defparam Umtl.DATA_WIDTH = 25;

// ---- Adder Tree Complete ---- 
wire [19:0] fir_int_res;
assign fir_int_res = atree_res [19:0];

assign fir_result = fir_int_res[ACCUM_WIDTH-1:0];
wire pre_rdy;
assign rdy_to_ld = pre_rdy;
assign done = done_int;
par_ctrl Uctrl(.rst(rst),
		.clk(clk),
		.clk_en(clk_en),
		.done(done_int),
		.rdy_int(rdy_int),
		.rdy_to_ld(pre_rdy));
defparam Uctrl.REG_LEN = 8;
defparam Uctrl.REG_BIT = 4;
defparam Uctrl.CH_WIDTH =0; 
defparam Uctrl.NUM_CH =1; 
endmodule
